#!/bin/bash
TASK="bench-batch --gnuplot=$1-update -Dpar=$2 -Dsz=$3 -Dlookups=$4 -Dinserts=$5 -Dremoves=$6 -Dtotalops=$7 ctries.MultiUpdateCtrie2 ctries.MultiUpdateSkipList ctries.MultiUpdateCHM"
sbt "$TASK"
