#!/bin/bash

if [ "$1" == "-h" ]; then
  echo "Runs all benchmarks. Synthax: bench-all <workstation> <numproc-range> <size-range> <lookups> <inserts> <removes> <totalops-for-bench-update> <pagerank-pagegenerator> <pagerank-maxlinks> <pagerank-damping> <pagerank-size>"
else
  tools/bench-insert $@
  tools/bench-lookup $@
  tools/bench-remove $@
  tools/bench-update $@
  tools/bench-snapshot $@
  tools/bench-iter $@
  tools/bench-pagerank $@
fi
