#!/usr/bin/perl

if ( @ARGV != 6 ) {
  print "Usage: totikz <source> <destin> <x-column> <z-column> <y-column> <process> \n";
  print "where: \n";
  print "  source - file with benchmark results \n";
  print "  destin - file to store the tikz graph into \n";
  print "  x-column - the index of the x-column, used for x-axis \n";
  print "  z-column - the index of the z-column, used for multiple graphs \n";
  print "  y-column - the index of the first y-column, used for curves in the graphs \n";
  print "  process - how to process the entry, one of: none, throughput \n";
  exit;
}


open(SOURCE, $ARGV[0]);
open(PLOT, ">$ARGV[1]") || die("Cannot Open File");
$x = $ARGV[2];
$z = $ARGV[3];
$y = $ARGV[4];
$proc = $ARGV[5];
%plots = ();
$gcount = 0;


sub process {
  print "$proc \n";
  if ($proc eq "none") { return $_[0]; }
  elsif ($proc eq "throughput") { return 1000 / $_[0]; }
  else { return $_[0]; }
}


while ($line = <SOURCE>) {
  #print "$line";
  @cells = split(/  | \n| /, $line);
  $len = @cells;
  #print "$len \n";
  $zcol = int(@cells[$z]);
  $plots{$zcol} = () if !exists $plots{$zcol};
  for ($n = $y; $n < $len; $n++) {
    $plots{$zcol}{$n} = () if !exists $plots{$zcol}{$n};
    $plots{$zcol}{$n}{@cells[$x]} = process(@cells[$n]);
    print "$n: process(@cells[$n]) \n";
  }
}


print PLOT "\\begin{figure}[h] \n";
print PLOT "\\begin{center} \n";
print PLOT "\\renewcommand{\\tabcolsep}{0cm} \n";
print PLOT "\\begin{tabular}{ c c c } \n";
print PLOT "\n";
foreach $graph (sort {$a <=> $b} (keys %plots)) {
  print "$graph: $plots{$graph} \n";
  print PLOT "\\begin{tikzpicture}[scale=0.67] \n";
  print PLOT "\\begin{axis}[height=5cm,width=5cm] \n";
  foreach $plot (sort(keys %{$plots{$graph}})) {
    print "  $plot: $plots{$graph}{$plot} \n";
    $mnum = $plot - $y;
    if ($mnum == 0) { $mark = ""; }
    if ($mnum == 1) { $mark = ",mark=o"; }
    if ($mnum == 2) { $mark = ",mark=x"; }
    if ($mnum == 3) { $mark = ",mark=*"; }
    print "$mnum \n";
    print PLOT "\\addplot[smooth$mark] \n";
    print PLOT "plot coordinates { \n";
    foreach $ntr (sort(keys %{$plots{$graph}{$plot}})) {
      print "    $ntr: $plots{$graph}{$plot}{$ntr} \n";
      print PLOT "($ntr, $plots{$graph}{$plot}{$ntr}) \n";
    }
    print PLOT "}; \n";
  }
  print PLOT "\\end{axis} \n";
  print PLOT "\\end{tikzpicture} \n";
  print PLOT "\n";
  $gcount++;
  if ($gcount % 3 != 0) { print PLOT "& \n"; }
  else { print PLOT "\\\\ \n"; }
  print PLOT "\n";
}
print PLOT "\n";
print PLOT "\\end{tabular} \n";
print PLOT "\\end{center} \n";
print PLOT "\n";
print PLOT "\\caption{Benchmark} \n";
print PLOT "\\label{f-bench} \n";
print PLOT "\\end{figure} \n";


close(SOURCE);
close(PLOT);
